name: Flask-app

on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 
      - name: Setup python
        uses: actions/setup-python@v2
      - name: run requirements
        run: pip install -r requirement.txt
      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"      
      - name: test case
        run: python test.py
      - name: deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key &&
          rsync -azP -e "ssh -i private_key -o StrictHostKeyChecking=no" app.py root@15.206.84.164:/root/test/ &&
          ssh -o StrictHostKeyChecking=no -i private_key root@15.206.84.164 '
          python3 app.py
          '
